export const SHOW_REGISTRATION_LOADING = 'REGISTRATION/SHOW_LOADING';
export const HIDE_REGISTRATION_LOADING = 'REGISTRATION/HIDE_LOADING';
export const REGISTRATION_SUCCESS = 'REGISTRATION/REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION/REGISTRATION_ERROR';
