export const SHOW_USER_PROFILE_LOADING = 'USER_PROFILE/SHOW_LOADING';
export const HIDE_USER_PROFILE_LOADING = 'USER_PROFILE/HIDE_LOADING';
export const LOAD_USER_PROFILE_SUCCESS = 'USER_PROFILE/LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_ERROR = 'USER_PROFILE/LOAD_USER_PROFILE_ERROR';
