export const SHOW_AUTHORIZATION_LOADING = 'AUTHORIZATION/SHOW_LOADING';
export const HIDE_AUTHORIZATION_LOADING = 'AUTHORIZATION/HIDE_LOADING';
export const LOAD_AUTHORIZATION_SUCCESS = 'AUTHORIZATION/LOAD_AUTHORIZATION_SUCCESS';
export const LOAD_AUTHORIZATION_ERROR = 'AUTHORIZATION/LOAD_AUTHORIZATION_ERROR';
export const LOAD_AUTHORIZATION_CANCEL = 'AUTHORIZATION/LOAD_AUTHORIZATION_CANCEL';
