export const SHOW_POSTCOMMENTS_LOADING = 'POSTCOMMENTS/SHOW_LOADING';
export const HIDE_POSTCOMMENTS_LOADING = 'POSTCOMMENTS/HIDE_LOADING';
export const LOAD_POSTCOMMENTS_SUCCESS = 'POSTCOMMENTS/LOAD_COMMENTS_SUCCESS';
export const LOAD_POSTCOMMENTS_ERROR = 'POSTCOMMENTS/LOAD_COMMENTS_ERROR';
export const SET_POSTCOMMENTS_CURRENT_PAGE = 'POSTCOMMENTS/SET_CURRENT_PAGE';
export const SET_POSTCOMMENTS_LIMIT = 'POSTCOMMENTS/SET_LIMIT';
export const SET_POSTCOMMENTS_TOTAL_COUNT = 'POSTCOMMENTS/SET_TOTAL_COUNT';
