export const SHOW_POSTS_LOADING = 'POSTS/SHOW_LOADING';
export const HIDE_POSTS_LOADING = 'POSTS/HIDE_LOADING';
export const LOAD_POSTS_SUCCESS = 'POSTS/LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_ERROR = 'POSTS/LOAD_POSTS_ERROR';
export const SET_POSTS_CURRENT_PAGE = 'POSTS/SET_CURRENT_PAGE';
export const SET_POSTS_LIMIT = 'POSTS/SET_LIMIT';
export const SET_POSTS_TOTAL_COUNT = 'POSTS/SET_TOTAL_COUNT';
