export const SHOW_USER_PROFILE_LOADING = 'USER_PROFILE/SHOW_LOADING';
export const HIDE_USER_PROFILE_LOADING = 'USER_PROFILE/HIDE_LOADING';
export const LOAD_USER_PROFILE_SUCCESS = 'USER_PROFILE/LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_ERROR = 'USER_PROFILE/LOAD_USER_PROFILE_ERROR';

export const SHOW_USER_PROFILE_EDIT_LOADING = 'USER_PROFILE_EDIT/SHOW_LOADING';
export const HIDE_USER_PROFILE_EDIT_LOADING = 'USER_PROFILE_EDIT/HIDE_LOADING';
export const USER_PROFILE_EDIT = 'USER_PROFILE_EDIT/UPDATE';
export const LOAD_USER_PROFILE_EDIT_SUCCESS = 'USER_PROFILE_EDIT/LOAD_USER_PROFILE_EDIT_SUCCESS';
export const LOAD_USER_PROFILE_EDIT_ERROR = 'USER_PROFILE_EDIT/LOAD_USER_PROFILE_EDIT_ERROR';

export const SHOW_UPLOAD_IMGBB_LOADING = 'UPLOAD_IMGBB/SHOW_LOADING';
export const HIDE_UPLOAD_IMGBB_LOADING = 'UPLOAD_IMGBB/HIDE_LOADING';
export const UPLOAD_IMGBB = 'UPLOAD_IMGBB/UPDATE';
export const LOAD_UPLOAD_IMGBB_SUCCESS = 'UPLOAD_IMGBB/LOAD_UPLOAD_IMGBB_SUCCESS';
export const LOAD_UPLOAD_IMGBB_ERROR = 'UPLOAD_IMGBB/LOAD_UPLOAD_IMGBB_ERROR';
