export const SHOW_USERS_LOADING = 'USERS/SHOW_LOADING';
export const HIDE_USERS_LOADING = 'USERS/HIDE_LOADING';
export const LOAD_USERS_SUCCESS = 'USERS/LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'USERS/LOAD_USERS_ERROR';
export const SET_USERS_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE';
export const SET_USERS_LIMIT = 'USERS/SET_LIMIT';
export const SET_USERS_TOTAL_COUNT = 'USERS/SET_TOTAL_COUNT';
